### ISSUE TITLE
Clicking the emoji button makes BD crash.

### ISSUE THREAD

**Issue by heartdeadz** [lolpowerluke/bd-themes#1]
**Describe the bug**
After i updated to 1.8.0 BD,  if i press the emoji button,  BD crashes.
first i thought it was my plugins and such, so i disabled them all,  kept crashing,  went into their support and asked around, and they told me to disable this theme, and  volia, BD stopped crashing!  figured i'd come here and let you know.

**To Reproduce**
1: Click the Emoji button.
2: BD goes from using 300MB of memory, to instantly 2000++, then it crashes.
3: this happens 100% of the time.

i've tried to disable everything but BD and this theme, and it just keeps on crashing.  same result every time too! huge memory leak, then it just crashes.

as soon as i disable the theme, it stops crashing :)

**Screenshots**
Added.

**additional info (please complete the following information):**
Windows 11
i am on what ever the official release is for discord.

![3dCqRslJYJ](https://user-images.githubusercontent.com/97589437/195388214-2ff240a3-8f25-4629-80d4-4ec1aa1faaa2.png)
![4dlUKhqyTK](https://user-images.githubusercontent.com/97589437/195388221-fd218774-7f1c-4898-88e3-3eda631f8547.png)

![195389359-ff384bd0-ec3e-40f8-b60a-afd82457fdd1](https://user-images.githubusercontent.com/97589437/195394362-876dc51f-9ce8-402d-9786-ccad811b7e32.png)
![195389365-4d87ac2f-6e76-4d0d-b235-1ebf38d96e88](https://user-images.githubusercontent.com/97589437/195394370-0c9d6a42-bfd6-4b8d-ae7e-40979ba6dc73.png)

**Comment by heartdeadz** [comment]
![gqLTxL4WNk](https://user-images.githubusercontent.com/97589437/195389359-ff384bd0-ec3e-40f8-b60a-afd82457fdd1.png)
![uhgqjCF0Yr](https://user-images.githubusercontent.com/97589437/195389365-4d87ac2f-6e76-4d0d-b235-1ebf38d96e88.png)

**Comment by lolpowerluke** [comment]
I see, thanks for letting me know
I'll look into it in the next couple of days

**Comment by lolpowerluke** [comment]
I cant reproduce this bug
1: are you sure you disabled all your plugins?
2: did you modify my theme in any way?
if yes: can you send me what modification you did, I can try to fix it if you want

**Comment by heartdeadz** [comment]
Hey there lolpowerluke! 
you know, i figured out what was up with it yesterday! was gonna update here as soon as i woke up! ( which i just did )

it totally slipped my mind that i did infact modify one piece of the theme! once i went back to the original, the error stopped happening!   so its 100% my own fault! 

again, my bad! i totally forgot ):  been using this theme for months and months, so i've gotten so used to it! haha

**Comment by lolpowerluke** [comment]
Its fine, I can try to fix it if you want to keep using it, but you'll have to sent me the code for that, and preferably an image or explanation as of what it changed

**Comment by heartdeadz** [comment]
oh man, you are fantastic for being willing to do that!  but i fixed it myself :D 
Thank you for this theme tho, hands down my favorite ever! haven't even used another since you released this one! :D

**Comment by lolpowerluke** [comment]
I see
glad to see that you like the theme
